---
engines:
  pmd:
    enabled: true
    config: dev-config/pmd/fluentlenium_pmd.xml
    channel: "beta"
  checkstyle:
    enabled: true
    config: dev-config/checkstyle/fluentlenium_checks.xml
    channel: "beta"
    checks:
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTypeCheck:
        enabled: false

ratings:
  paths:
  - "**.java"

exclude_paths: []
