---
version: 2

plugins:
  checkstyle:
    enabled: true
    config:
      file: dev-config/checkstyle/fluentlenium_checks.xml

  pmd:
    enabled: true
    config:
      file: dev-config/pmd/fluentlenium_pmd.xml

ratings:
  paths:
  - "**.java"
  - "**.groovy"

exclude_patterns:
  - "**/*.js"
  - "**/*.html"
  - "**/*.kt"
  - "docs/"
