---
plugins:
  checkstyle:
    enabled: true
    config:
      file: dev-config/checkstyle/fluentlenium_checks.xml

engines:
  pmd:
    enabled: true
    config: dev-config/pmd/fluentlenium_pmd.xml
    channel: "beta"

ratings:
  paths:
  - "**.java"
  - "**.groovy"

exclude_patterns:
  - "**/*.js"
  - "**/*.html"
  - "**/*.kt"
  - "docs/"
