name: 'Setup environment'
description: "install java, maven wrapper & checkout repo"

inputs:
  java-version:
    description: 'java version to install'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'zulu'
        cache: "maven"

    - name: Cache Maven Wrapper
      uses: actions/cache@v4
      with:
        key: mavenWrapper-${{ hashfiles('.mvn/wrapper/maven-wrapper.*') }}
        path: ~/.m2/wrapper
