name: 'Maven install Fluentlenium (no tests)'
description: "this will build & install fluentlenium to the local repo"
runs:
  using: "composite"
  steps:
    - name: run maven install
      run: ./mvnw -B clean install -DskipTests=true
      shell: bash
      env:
        MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.javadoc.skip"
