name: 'Publish Buildscan'
description: "publish build in Github Action summary"

runs:
  using: "composite"
  steps:
    - name: show build scan URL in summary
      shell: bash
      run: |
        tail -100 build.log
        BUILD_SCAN=$(tail -100 build.log|grep -oP '\[INFO\] \Khttps://gradle.com/[\w\/.]*')
    
        echo "Build scan url is $BUILD_SCAN"
    
        if [[ ! -z "$BUILD_SCAN" ]]
        then
          BADGE_URL=https://img.shields.io/badge/Build%20Scan%E2%84%A2-PUBLISHED-06A0CE?logo=Gradle
          BADGE_HTML="<img src=\"${BADGE_URL}\" alt=\"Build Scan Published\" />"
          URL="<a href=\"${BUILD_SCAN}\" rel=\"nofollow\">${BADGE_HTML}</a>"
    
          echo "$URL" >> $GITHUB_STEP_SUMMARY
        fi
